# Generated by Django 2.2.2 on 2019-06-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(max_length=100)),
                ('genome_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=1000)),
                ('patric_id', models.CharField(max_length=100)),
                ('fig_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('genome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.GenomeModel')),
            ],
        ),
    ]
