# Generated by Django 2.2.5 on 2019-11-19 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(max_length=1000)),
                ('genome_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GenomeUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_id', models.CharField(max_length=1000)),
                ('last_used', models.DateTimeField(default=datetime.datetime.now)),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.JobModel')),
            ],
        ),
        migrations.CreateModel(
            name='MotifSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finder.JobModel')),
            ],
        ),
        migrations.CreateModel(
            name='MotifModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_text', models.CharField(max_length=1000)),
                ('in_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.MotifSearchModel')),
            ],
        ),
        migrations.CreateModel(
            name='HMMSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmm_path', models.CharField(max_length=500)),
                ('threshold', models.FloatField()),
                ('gene_name', models.CharField(max_length=200)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finder.JobModel')),
            ],
        ),
        migrations.CreateModel(
            name='GeneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('sequence', models.CharField(max_length=10000)),
                ('patric_id', models.CharField(max_length=100)),
                ('fig_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('in_genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.GenomeModel')),
            ],
        ),
    ]
