# Generated by Django 2.2.2 on 2019-06-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genemodel',
            old_name='genome_id',
            new_name='in_genome',
        ),
    ]
