# Generated by Django 2.2.2 on 2019-06-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20190627_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=100)),
                ('motif_text', models.CharField(max_length=100)),
            ],
        ),
    ]
