# Generated by Django 2.2.5 on 2019-09-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_motifsearchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genemodel',
            name='fig_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='genemodel',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='genemodel',
            name='patric_id',
            field=models.CharField(max_length=1000),
        ),
    ]
