# Generated by Django 2.2.5 on 2019-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20190904_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genemodel',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='genemodel',
            name='fig_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='genemodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='genemodel',
            name='patric_id',
            field=models.CharField(max_length=300),
        ),
    ]
