# Generated by Django 2.2.5 on 2019-09-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20190908_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genemodel',
            name='sequence',
            field=models.CharField(max_length=10000),
        ),
    ]
