# Generated by Django 2.2.5 on 2019-09-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_auto_20190912_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motifsearchmodel',
            name='motif_text',
            field=models.CharField(max_length=1000),
        ),
    ]
