# Generated by Django 2.2.5 on 2019-09-13 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20190912_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motifsearchmodel',
            name='motif_text',
        ),
        migrations.CreateModel(
            name='MotifModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_text', models.CharField(max_length=1000)),
                ('in_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.MotifSearchModel')),
            ],
        ),
    ]
