# Generated by Django 2.2.5 on 2019-10-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20190913_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMMModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmm_path', models.CharField(max_length=500)),
                ('threshold', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
