# Generated by Django 2.2.5 on 2019-10-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_hmmmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HMMModel',
            new_name='HMMSearchModel',
        ),
    ]
