# Generated by Django 2.2.5 on 2019-10-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_auto_20191014_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmmsearchmodel',
            old_name='name',
            new_name='gene_name',
        ),
    ]
